### PR TITLE
WIP 106: Brought nav menu to the top under the header, hovers working, cur…

### PR DESCRIPTION
**Pull request by christopherdavidbach**
…rent page working, and responsive

### CODE REVIEW

**Comment by rcaracaus** [comment]
Let's get this menu looking more like this 

screen shot 2016-07-06 at 11 47 13 am

**Comment by rcaracaus** [comment]
Stil not re-rolled after I asked to re-roll yesterday

**Comment by christopherdavidbach** [comment]
There is still in issue in Nav/index.jsx, I'm looking in to it now

**Comment by christopherdavidbach** [comment]
screen shot 2016-07-13 at 9 40 42 am

I can't find the issue. I have made a note to ask Elijah about it when he comes online.

**Comment by rcaracaus** [comment]
Please remove home button

**Comment by rcaracaus** [comment]
Make logo link to homepage

**Pull request merged**
