### PR TITLE
125: Adding Typography changes and basic layout for blogdetail

### PR DESCRIPTION
**Pull request by astolfivincent**
-Go To /blog/ and click on any of the listings to view

### CODE REVIEW

**Comment by rcaracaus** [comment]
Need name, date, tags. Needs styleguide example. Then should be good to merge.

**Comment by rcaracaus** [comment]
Tags and Author name should be at the top, put your "About the Author" block in another branch or WIP PR and we can get it in after teams infra is set up

**Comment by rcaracaus** [comment]
Please remove dotted line, even out spacing, the meta information should be closer to the title than the body. Also make larger please. Tags should use same style as listing, no reason to have totally different, and remove labels.

**Comment by rcaracaus** [comment]
This page's CSS isn't working https://desarol-pr-144.herokuapp.com/styleguide/section-blog-detail.html#kssref-blog-detail

**Comment by rcaracaus** [comment]
We need examples of links, bold, underline, and italic

**Comment by rcaracaus** [comment]
You added gray matter stuff to this typography PR FYI

**Comment by astolfivincent** [comment]
I know I needed the stuff from that.

**Comment by rcaracaus** [comment]
Well we will merge that then first

**Comment by astolfivincent** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#emphasis

Doesn't look like "underlined" text is supported in Markdown, at least not out of the box. Everything else I'll commit right now and you can see the examples of each on the /blog listing page

**Comment by rcaracaus** [comment]
Underline not important, just made that up.

**Comment by rcaracaus** [comment]
Still not able to see this in the styleguide https://desarol-pr-144.herokuapp.com/styleguide/section-blog-detail.html#

**Pull request merged**
